# Generated by Django 2.2.9 on 2022-03-08 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=122)),
                ('idade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('unidade', models.CharField(choices=[('ZONA_SUL', 'ZS'), ('ZONA_LESTE', 'ZL'), ('ZONA_OESTE', 'ZO'), ('ZONA_NORTE', 'ZN')], max_length=11)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=122)),
                ('unidade', models.CharField(choices=[('ZONA_SUL', 'ZS'), ('ZONA_LESTE', 'ZL'), ('ZONA_OESTE', 'ZO'), ('ZONA_NORTE', 'ZN')], max_length=11)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
    ]
