# Generated by Django 2.2.9 on 2022-03-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registro',
        ),
    ]
